// Supabase admin client used by JV server routes to read/write the
// `app_rows` table on behalf of users. We use the SERVICE ROLE KEY which
// bypasses RLS — security is enforced at our route layer (ownership check
// via the app_id → projects/apps lookup), not in Postgres.
//
// Why service role: the alternative would be passing each user's JWT through
// to Supabase, but our users authenticate via OUR system (jose JWT), not
// Supabase Auth. Going through Supabase Auth would add a whole second
// identity system. Service-key + careful route auth is simpler.
//
// Env vars (set in .env on the server + DEPLOY_ENV GH secret):
//   SUPABASE_URL=https://<project>.supabase.co
//   SUPABASE_SERVICE_KEY=<service_role secret>  ⚠ NEVER expose to client

import { createClient, type SupabaseClient } from "@supabase/supabase-js";

let _client: SupabaseClient | null = null;

export function supabaseConfigured(): boolean {
  return !!(process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_KEY);
}

export function getSupabase(): SupabaseClient {
  if (_client) return _client;
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_KEY;
  if (!url || !key) {
    throw new Error(
      "Supabase chưa cấu hình — set SUPABASE_URL + SUPABASE_SERVICE_KEY trong .env",
    );
  }
  _client = createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
  return _client;
}

// Row shape stored in app_rows. row_data is freeform JSON so each app can
// have its own schema without us pre-declaring columns.
export interface AppRow {
  id: string;          // uuid generated by Supabase default
  app_id: string;
  table_name: string;  // logical sub-namespace (e.g. "submissions", "products")
  row_data: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface SelectOptions {
  limit?: number;
  orderDesc?: boolean; // default true (newest first)
  where?: Record<string, string | number | boolean | null>;
}

// SELECT — newest first by default. `where` does exact-match on row_data keys.
// For richer queries, callers can use the raw supabase client.
export async function selectRows(
  app_id: string,
  table_name: string,
  opts: SelectOptions = {},
): Promise<AppRow[]> {
  const sb = getSupabase();
  let q = sb
    .from("app_rows")
    .select("*")
    .eq("app_id", app_id)
    .eq("table_name", table_name)
    .order("created_at", { ascending: !(opts.orderDesc ?? true) })
    .limit(opts.limit ?? 100);
  if (opts.where) {
    for (const [k, v] of Object.entries(opts.where)) {
      // Postgres JSONB path query via contains (->) → equality on a field.
      q = q.eq(`row_data->>${k}`, String(v));
    }
  }
  const { data, error } = await q;
  if (error) throw new Error(`supabase select: ${error.message}`);
  return (data as AppRow[]) ?? [];
}

// INSERT one row. row_data is the freeform JSON payload.
export async function insertRow(
  app_id: string,
  table_name: string,
  row_data: Record<string, unknown>,
): Promise<AppRow> {
  const sb = getSupabase();
  const { data, error } = await sb
    .from("app_rows")
    .insert({ app_id, table_name, row_data })
    .select()
    .single();
  if (error) throw new Error(`supabase insert: ${error.message}`);
  return data as AppRow;
}

// UPDATE — replaces row_data with merged fields (sparse). Caller passes only
// the keys they want changed.
export async function updateRow(
  app_id: string,
  table_name: string,
  rowId: string,
  fields: Record<string, unknown>,
): Promise<AppRow> {
  const sb = getSupabase();
  // Fetch existing first to merge — Supabase JSON update isn't trivial.
  const { data: existing, error: getErr } = await sb
    .from("app_rows")
    .select("row_data")
    .eq("id", rowId)
    .eq("app_id", app_id)
    .single();
  if (getErr) throw new Error(`supabase get-before-update: ${getErr.message}`);
  const merged = { ...(existing?.row_data ?? {}), ...fields };
  const { data, error } = await sb
    .from("app_rows")
    .update({ row_data: merged, updated_at: new Date().toISOString() })
    .eq("id", rowId)
    .eq("app_id", app_id)
    .eq("table_name", table_name)
    .select()
    .single();
  if (error) throw new Error(`supabase update: ${error.message}`);
  return data as AppRow;
}

export async function deleteRow(
  app_id: string,
  table_name: string,
  rowId: string,
): Promise<void> {
  const sb = getSupabase();
  const { error } = await sb
    .from("app_rows")
    .delete()
    .eq("id", rowId)
    .eq("app_id", app_id)
    .eq("table_name", table_name);
  if (error) throw new Error(`supabase delete: ${error.message}`);
}

// Distinct table_names an app has used — handy for the dashboard to list
// "Submissions", "Products", etc.
export async function listTables(app_id: string): Promise<string[]> {
  const sb = getSupabase();
  const { data, error } = await sb
    .from("app_rows")
    .select("table_name")
    .eq("app_id", app_id)
    .limit(1000);
  if (error) throw new Error(`supabase list tables: ${error.message}`);
  const seen = new Set<string>();
  for (const r of (data ?? []) as Array<{ table_name: string }>) {
    seen.add(r.table_name);
  }
  return Array.from(seen).sort();
}
